language: python

python:
  - 3.5.1

services:
  - postgresql

env:
  - DJANGO=1.9

before_install:
  - export SECRET_KEY=$SECRET_KEY
  - export DJANGO_SETTINGS_MODULE=pigeonly_test.travis-settings
  - export PYTHONPATH=$HOME/builds/pigeonly_test
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE pigeonly_test;" -U postgres
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test phone_number_parser

after_success:
  - coveralls
